# Model Specification
model: DeepSnake
model_args:
  backbone: Xception
  model_dim: 1024
  iterations: 4
  coord_features: true
  stop_grad: true
  head: SnakeHead
loss_function: SoftDTW(0.001, 8)
# Data args
batch_size: 16
data_root: '../CALFIN/training/data'
tile_size: 256
vertices: 64
